import forms from '@tailwindcss/forms'

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#191206',
        'surface-dim': '#191206',
        'surface-bright': '#413829',
        'surface-container-lowest': '#130d03',
        'surface-container-low': '#221b0d',
        'surface-container': 'rgb(var(--c-surface-container) / <alpha-value>)',
        'surface-container-high': 'rgb(var(--c-surface-container-high) / <alpha-value>)',
        'surface-container-highest': '#3c3425',
        'on-surface': 'rgb(var(--c-on-surface) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--c-on-surface-variant) / <alpha-value>)',
        'inverse-surface': '#efe1cb',
        'inverse-on-surface': '#382f21',
        outline: 'rgb(var(--c-outline) / <alpha-value>)',
        'outline-variant': 'rgb(var(--c-outline-variant) / <alpha-value>)',
        'surface-tint': '#ffb4a2',
        primary: '#ffb4a2',
        'on-primary': '#522216',
        'primary-container': '#4a1c10',
        'on-primary-container': '#c5806e',
        'inverse-primary': '#8a4e3f',
        secondary: 'rgb(var(--c-secondary) / <alpha-value>)',
        'on-secondary': '#4a2808',
        'secondary-container': 'rgb(var(--c-secondary-container) / <alpha-value>)',
        'on-secondary-container': '#e0aa80',
        'secondary-fixed': 'rgb(var(--c-secondary-fixed) / <alpha-value>)',
        'secondary-fixed-dim': '#f3bb90',
        tertiary: '#ffb4aa',
        'on-tertiary': '#5d1712',
        'tertiary-container': '#55110d',
        'on-tertiary-container': '#d9756a',
        error: 'rgb(var(--c-error) / <alpha-value>)',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        background: '#191206',
        'on-background': '#efe1cb',
        brass: '#B8860B',
        'brass-light': '#C8956C',
        'bronze-muted': '#8B6942',
        'espresso': '#2C1810',
      },
      fontFamily: {
        display: ['Inter', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        engraved: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', fontWeight: '700', letterSpacing: '-0.02em' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', fontWeight: '700', letterSpacing: '-0.01em' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '600', letterSpacing: '0.05em' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      spacing: {
        'xs': '4px',
        'sm': '12px',
        'md': '24px',
        'lg': '48px',
        'xl': '80px',
        'gutter': '24px',
        'container-max': '1280px',
        'margin-mobile': '16px',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.5rem',
      },
      boxShadow: {
        'amber-glow': '0 0 20px rgba(255, 191, 0, 0.15)',
        'amber-glow-lg': '0 0 25px rgba(255, 191, 0, 0.25)',
        'glass': '0 20px 40px -10px rgba(0, 0, 0, 0.7)',
      },
    },
  },
  plugins: [forms],
}
