CREATE TABLE push_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id BIGINT NOT NULL REFERENCES salons(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    audience VARCHAR(16) NOT NULL,
    endpoint VARCHAR(2048) NOT NULL,
    endpoint_hash CHAR(64) NOT NULL,
    p256dh VARCHAR(512) NOT NULL,
    auth VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT push_subscriptions_audience_check CHECK (audience IN ('CUSTOMER','OWNER')),
    CONSTRAINT push_subscriptions_endpoint_unique
        UNIQUE (salon_id, user_id, audience, endpoint_hash)
);

CREATE INDEX idx_push_subscriptions_recipient
    ON push_subscriptions(salon_id, user_id, audience);

CREATE TABLE push_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id BIGINT NOT NULL REFERENCES salons(id) ON DELETE CASCADE,
    booking_id BIGINT NOT NULL,
    subscription_id BIGINT REFERENCES push_subscriptions(id) ON DELETE SET NULL,
    recipient_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    event_key VARCHAR(255) NOT NULL,
    notification_type VARCHAR(40) NOT NULL,
    endpoint VARCHAR(2048) NOT NULL,
    p256dh VARCHAR(512) NOT NULL,
    auth VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    body VARCHAR(500) NOT NULL,
    target_url VARCHAR(2048) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    claimed_by VARCHAR(64),
    claimed_until TIMESTAMP WITH TIME ZONE,
    sent_at TIMESTAMP WITH TIME ZONE,
    discarded_at TIMESTAMP WITH TIME ZONE,
    last_error VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT push_outbox_booking_fk FOREIGN KEY (booking_id, salon_id)
        REFERENCES bookings(id, salon_id) ON DELETE CASCADE,
    CONSTRAINT push_outbox_event_unique UNIQUE (salon_id, event_key),
    CONSTRAINT push_outbox_attempt_count_check CHECK (attempt_count >= 0)
);

CREATE INDEX idx_push_outbox_delivery
    ON push_outbox(next_attempt_at, id);
CREATE INDEX idx_push_outbox_salon_booking
    ON push_outbox(salon_id, booking_id);
