CREATE TABLE promotions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id BIGINT NOT NULL REFERENCES salons(id) ON DELETE CASCADE,
    code VARCHAR(40) NOT NULL,
    code_normalized VARCHAR(40) NOT NULL,
    discount_type VARCHAR(16) NOT NULL,
    discount_value NUMERIC(12, 2) NOT NULL,
    starts_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ends_at TIMESTAMP WITH TIME ZONE NOT NULL,
    total_limit INTEGER,
    per_customer_limit INTEGER,
    minimum_spend NUMERIC(12, 2) NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT promotions_code_unique UNIQUE (salon_id, code_normalized),
    CONSTRAINT promotions_code_normalized_check
        CHECK (code_normalized = UPPER(TRIM(code_normalized)) AND LENGTH(code_normalized) >= 2),
    CONSTRAINT promotions_id_salon_unique UNIQUE (id, salon_id),
    CONSTRAINT promotions_type_check CHECK (discount_type IN ('PERCENT', 'FIXED')),
    CONSTRAINT promotions_value_check CHECK (discount_value > 0
        AND (discount_type <> 'PERCENT' OR discount_value <= 100)),
    CONSTRAINT promotions_window_check CHECK (starts_at < ends_at),
    CONSTRAINT promotions_total_limit_check CHECK (total_limit IS NULL OR total_limit > 0),
    CONSTRAINT promotions_customer_limit_check
        CHECK (per_customer_limit IS NULL OR per_customer_limit > 0),
    CONSTRAINT promotions_minimum_spend_check CHECK (minimum_spend >= 0)
);

CREATE TABLE promotion_services (
    salon_id BIGINT NOT NULL REFERENCES salons(id) ON DELETE CASCADE,
    promotion_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    PRIMARY KEY (salon_id, promotion_id, service_id),
    CONSTRAINT promotion_services_promotion_fk FOREIGN KEY (promotion_id, salon_id)
        REFERENCES promotions(id, salon_id) ON DELETE CASCADE,
    CONSTRAINT promotion_services_service_fk FOREIGN KEY (service_id, salon_id)
        REFERENCES services(id, salon_id) ON DELETE CASCADE
);
ALTER TABLE bookings ADD COLUMN original_price NUMERIC(12, 2);
ALTER TABLE bookings ADD COLUMN discount_amount NUMERIC(12, 2);
ALTER TABLE bookings ADD COLUMN promo_code VARCHAR(40);

UPDATE bookings SET original_price = price_snapshot, discount_amount = 0;
ALTER TABLE bookings ALTER COLUMN original_price SET NOT NULL;
ALTER TABLE bookings ALTER COLUMN discount_amount SET NOT NULL;
ALTER TABLE bookings ALTER COLUMN discount_amount SET DEFAULT 0;
ALTER TABLE bookings ADD CONSTRAINT bookings_original_price_check CHECK (original_price >= 0);
ALTER TABLE bookings ADD CONSTRAINT bookings_discount_amount_check CHECK (
    discount_amount >= 0 AND discount_amount <= original_price
    AND price_snapshot = original_price - discount_amount
);

CREATE TABLE promotion_redemptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id BIGINT NOT NULL REFERENCES salons(id) ON DELETE CASCADE,
    promotion_id BIGINT NOT NULL,
    booking_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    status VARCHAR(16) NOT NULL DEFAULT 'RESERVED',
    discount_amount NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    released_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT promotion_redemptions_promotion_fk FOREIGN KEY (promotion_id, salon_id)
        REFERENCES promotions(id, salon_id) ON DELETE RESTRICT,
    CONSTRAINT promotion_redemptions_booking_fk FOREIGN KEY (booking_id, salon_id)
        REFERENCES bookings(id, salon_id) ON DELETE CASCADE,
    CONSTRAINT promotion_redemptions_booking_unique UNIQUE (salon_id, booking_id),
    CONSTRAINT promotion_redemptions_status_check CHECK (status IN ('RESERVED', 'RELEASED')),
    CONSTRAINT promotion_redemptions_discount_check CHECK (discount_amount >= 0)
);

CREATE INDEX idx_promotions_salon_active_window
    ON promotions(salon_id, is_active, starts_at, ends_at);
CREATE INDEX idx_promotion_redemptions_limit
    ON promotion_redemptions(salon_id, promotion_id, status, customer_id);
