CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(32) NOT NULL,
    phone VARCHAR(32),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_role_check CHECK (role IN ('CUSTOMER', 'SALON_OWNER', 'PLATFORM_ADMIN'))
);

CREATE TABLE salons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES users(id),
    subdomain VARCHAR(30) NOT NULL UNIQUE,
    name VARCHAR(160) NOT NULL,
    description TEXT,
    address TEXT NOT NULL,
    city VARCHAR(120) NOT NULL,
    phone VARCHAR(32),
    email VARCHAR(320),
    logo_url TEXT,
    timezone VARCHAR(64) NOT NULL DEFAULT 'UTC',
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    cancellation_window_minutes INTEGER NOT NULL DEFAULT 120,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT salons_subdomain_format_check CHECK (subdomain ~ '^[a-z0-9][a-z0-9-]{1,28}[a-z0-9]$'),
    CONSTRAINT salons_reserved_subdomain_check CHECK (subdomain NOT IN ('www', 'api', 'admin', 'app', 'mail')),
    CONSTRAINT salons_status_check CHECK (status IN ('PENDING', 'ACTIVE', 'SUSPENDED')),
    CONSTRAINT salons_cancellation_window_check CHECK (cancellation_window_minutes >= 0)
);

CREATE INDEX idx_salons_owner_id ON salons(owner_id);
CREATE INDEX idx_salons_city_status ON salons(city, status);

CREATE TABLE salon_photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id BIGINT NOT NULL REFERENCES salons(id) ON DELETE CASCADE,
    photo_url TEXT NOT NULL,
    alt_text VARCHAR(255),
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT salon_photos_sort_order_check CHECK (sort_order >= 0)
);
CREATE INDEX idx_salon_photos_salon_id ON salon_photos(salon_id);

CREATE TABLE salon_staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id BIGINT NOT NULL REFERENCES salons(id) ON DELETE CASCADE,
    name VARCHAR(160) NOT NULL,
    photo_url TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT salon_staff_id_salon_unique UNIQUE (id, salon_id)
);

CREATE INDEX idx_salon_staff_salon_active ON salon_staff(salon_id, is_active);

CREATE TABLE staff_working_hours (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id BIGINT NOT NULL REFERENCES salons(id) ON DELETE CASCADE,
    staff_id BIGINT NOT NULL,
    day_of_week SMALLINT NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    CONSTRAINT staff_working_hours_staff_fk FOREIGN KEY (staff_id, salon_id)
        REFERENCES salon_staff(id, salon_id) ON DELETE CASCADE,
    CONSTRAINT staff_working_hours_day_check CHECK (day_of_week BETWEEN 0 AND 6),
    CONSTRAINT staff_working_hours_range_check CHECK (start_time < end_time),
    CONSTRAINT staff_working_hours_unique UNIQUE (salon_id, staff_id, day_of_week, start_time)
);

CREATE INDEX idx_staff_working_hours_salon_staff ON staff_working_hours(salon_id, staff_id);

CREATE TABLE staff_time_off (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id BIGINT NOT NULL REFERENCES salons(id) ON DELETE CASCADE,
    staff_id BIGINT NOT NULL,
    start_datetime TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_datetime TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    reason VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT staff_time_off_staff_fk FOREIGN KEY (staff_id, salon_id)
        REFERENCES salon_staff(id, salon_id) ON DELETE CASCADE,
    CONSTRAINT staff_time_off_range_check CHECK (start_datetime < end_datetime)
);

CREATE INDEX idx_staff_time_off_salon_staff_start ON staff_time_off(salon_id, staff_id, start_datetime);
CREATE TABLE services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id BIGINT NOT NULL REFERENCES salons(id) ON DELETE CASCADE,
    name VARCHAR(160) NOT NULL,
    duration_minutes INTEGER NOT NULL,
    price NUMERIC(12, 2) NOT NULL,
    category VARCHAR(120),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT services_duration_check CHECK (duration_minutes BETWEEN 15 AND 180),
    CONSTRAINT services_price_check CHECK (price >= 0),
    CONSTRAINT services_id_salon_unique UNIQUE (id, salon_id)
);

CREATE INDEX idx_services_salon_active ON services(salon_id, is_active);

CREATE TABLE staff_services (
    salon_id BIGINT NOT NULL REFERENCES salons(id) ON DELETE CASCADE,
    staff_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (salon_id, staff_id, service_id),
    CONSTRAINT staff_services_staff_fk FOREIGN KEY (staff_id, salon_id)
        REFERENCES salon_staff(id, salon_id) ON DELETE CASCADE,
    CONSTRAINT staff_services_service_fk FOREIGN KEY (service_id, salon_id)
        REFERENCES services(id, salon_id) ON DELETE CASCADE
);

CREATE INDEX idx_staff_services_salon_service ON staff_services(salon_id, service_id);

CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id BIGINT NOT NULL REFERENCES salons(id) ON DELETE RESTRICT,
    customer_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    staff_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    start_datetime TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_datetime TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'CONFIRMED',
    price_snapshot NUMERIC(12, 2) NOT NULL,
    service_name_snapshot VARCHAR(160) NOT NULL,
    idempotency_key VARCHAR(128),
    reminder_24h_sent_at TIMESTAMP WITH TIME ZONE,
    reminder_1h_sent_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cancelled_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT bookings_staff_fk FOREIGN KEY (staff_id, salon_id)
        REFERENCES salon_staff(id, salon_id) ON DELETE RESTRICT,
    CONSTRAINT bookings_service_fk FOREIGN KEY (service_id, salon_id)
        REFERENCES services(id, salon_id) ON DELETE RESTRICT,
    CONSTRAINT bookings_range_check CHECK (start_datetime < end_datetime),
    CONSTRAINT bookings_status_check CHECK (status IN ('CONFIRMED', 'CANCELLED', 'COMPLETED', 'NO_SHOW')),
    CONSTRAINT bookings_price_snapshot_check CHECK (price_snapshot >= 0),
    CONSTRAINT bookings_id_salon_unique UNIQUE (id, salon_id),
    CONSTRAINT no_overlapping_bookings EXCLUDE USING gist (
        staff_id WITH =,
        tsrange(start_datetime, end_datetime) WITH &&
    ) WHERE (status = 'CONFIRMED')
);

CREATE UNIQUE INDEX uq_bookings_idempotency
    ON bookings(salon_id, customer_id, idempotency_key)
    WHERE idempotency_key IS NOT NULL;
CREATE INDEX idx_bookings_salon_start ON bookings(salon_id, start_datetime);
CREATE INDEX idx_bookings_salon_staff_start ON bookings(salon_id, staff_id, start_datetime);
CREATE INDEX idx_bookings_customer_start ON bookings(customer_id, start_datetime);
CREATE INDEX idx_bookings_pending_24h_reminder
    ON bookings(start_datetime)
    WHERE status = 'CONFIRMED' AND reminder_24h_sent_at IS NULL;
CREATE INDEX idx_bookings_pending_1h_reminder
    ON bookings(start_datetime)
    WHERE status = 'CONFIRMED' AND reminder_1h_sent_at IS NULL;

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id BIGINT NOT NULL REFERENCES salons(id) ON DELETE CASCADE,
    booking_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    rating SMALLINT NOT NULL,
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT reviews_booking_fk FOREIGN KEY (booking_id, salon_id)
        REFERENCES bookings(id, salon_id) ON DELETE CASCADE,
    CONSTRAINT reviews_rating_check CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT reviews_booking_unique UNIQUE (booking_id)
);

CREATE INDEX idx_reviews_salon_created ON reviews(salon_id, created_at DESC);
CREATE INDEX idx_reviews_salon_rating ON reviews(salon_id, rating);
