-- Google Business profile import: aggregate rating/count + place link on the salon,
-- imported 5-star reviews in their own table, and a source marker on photos so a
-- re-sync can replace only the Google-imported ones.

ALTER TABLE salons ADD COLUMN google_place_id TEXT;
ALTER TABLE salons ADD COLUMN google_rating NUMERIC(2, 1);
ALTER TABLE salons ADD COLUMN google_review_count INTEGER;
ALTER TABLE salons ADD COLUMN google_maps_uri TEXT;
ALTER TABLE salons ADD COLUMN google_synced_at TIMESTAMP WITH TIME ZONE;

-- Marks which salon_photos rows came from a Google sync so they can be swapped out.
ALTER TABLE salon_photos ADD COLUMN source VARCHAR(16) NOT NULL DEFAULT 'MANUAL';

CREATE TABLE google_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id BIGINT NOT NULL REFERENCES salons(id) ON DELETE CASCADE,
    author_name VARCHAR(255),
    author_photo_url TEXT,
    rating SMALLINT NOT NULL,
    text TEXT,
    relative_time VARCHAR(120),
    published_at TIMESTAMP WITH TIME ZONE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_google_reviews_salon_id ON google_reviews (salon_id);
