-- Referral program: a REFERRER account submits salons they refer; an admin
-- verifies, then pays. History is immutable once submitted.

-- Allow the new REFERRER role on the users table.
ALTER TABLE users DROP CONSTRAINT users_role_check;
ALTER TABLE users ADD CONSTRAINT users_role_check
    CHECK (role IN ('CUSTOMER', 'SALON_OWNER', 'PLATFORM_ADMIN', 'REFERRER'));

-- One profile per referrer user: their unique code, admin approval and the
-- per-referral payout amount the admin sets for them.
CREATE TABLE referrer_profiles (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    referral_code VARCHAR(16) NOT NULL UNIQUE,
    approved BOOLEAN NOT NULL DEFAULT FALSE,
    per_referral_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT referrer_profiles_amount_check CHECK (per_referral_amount >= 0)
);

-- A submitted referral. Once created the salon details cannot change; only the
-- status/amount move forward through the admin workflow.
CREATE TABLE referral_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referrer_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    salon_name VARCHAR(160) NOT NULL,
    salon_phone VARCHAR(32) NOT NULL,
    salon_phone_normalized VARCHAR(32) NOT NULL,
    maps_url TEXT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'VERIFYING',
    amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    reject_reason VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    decided_at TIMESTAMP WITH TIME ZONE,
    paid_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT referral_submissions_status_check
        CHECK (status IN ('VERIFYING', 'PENDING', 'PAID', 'REJECTED')),
    CONSTRAINT referral_submissions_amount_check CHECK (amount >= 0)
);

CREATE INDEX idx_referral_submissions_referrer ON referral_submissions(referrer_id);
CREATE INDEX idx_referral_submissions_status ON referral_submissions(status);

-- A salon (by normalized phone) can only have one active referral: once someone
-- has referred it and it is not rejected, no one else can claim it. Rejected rows
-- are excluded so a bad submission does not permanently block the salon.
CREATE UNIQUE INDEX uq_referral_active_salon_phone
    ON referral_submissions(salon_phone_normalized)
    WHERE status <> 'REJECTED';
