-- Lead distribution for referrers. Leads come from an external scraper API and
-- are handed out in batches; each assignment is recorded so leads are not repeated
-- and daily quotas / onboarding gates can be enforced. A referrer can be put on
-- hold (auto after failing the daily onboard target, or by an admin).

ALTER TABLE referrer_profiles ADD COLUMN on_hold BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE referrer_profiles ADD COLUMN hold_reason VARCHAR(255);

-- One row per lead delivered to a referrer. external_id is the lead's id from the
-- scraper app; unique per referrer so the same lead is never re-served to them.
-- submission_id links to the referral_submissions row auto-created for the lead,
-- so marking that submission PAID counts as an onboard.
CREATE TABLE referral_leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referrer_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    external_id VARCHAR(128) NOT NULL,
    submission_id BIGINT REFERENCES referral_submissions(id) ON DELETE SET NULL,
    assigned_on DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Globally claimed so two referrers never get the same scraped salon.
    CONSTRAINT uq_referral_leads_external UNIQUE (external_id)
);

CREATE INDEX idx_referral_leads_referrer_day ON referral_leads(referrer_id, assigned_on);
