CREATE TABLE notification_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id BIGINT NOT NULL REFERENCES salons(id) ON DELETE CASCADE,
    booking_id BIGINT NOT NULL,
    event_key VARCHAR(255) NOT NULL,
    notification_type VARCHAR(40) NOT NULL,
    recipient_email VARCHAR(320) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    claimed_by VARCHAR(64),
    claimed_until TIMESTAMP WITH TIME ZONE,
    sent_at TIMESTAMP WITH TIME ZONE,
    last_error VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT notification_outbox_booking_fk FOREIGN KEY (booking_id, salon_id)
        REFERENCES bookings(id, salon_id) ON DELETE CASCADE,
    CONSTRAINT notification_outbox_event_unique UNIQUE (salon_id, event_key),
    CONSTRAINT notification_outbox_attempt_count_check CHECK (attempt_count >= 0)
);

CREATE INDEX idx_notification_outbox_delivery
    ON notification_outbox(next_attempt_at, id)
    WHERE sent_at IS NULL;
CREATE INDEX idx_notification_outbox_salon_booking
    ON notification_outbox(salon_id, booking_id);
