ALTER TABLE users ADD COLUMN phone_verified_at TIMESTAMP WITH TIME ZONE;

CREATE TABLE auth_challenges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    challenge_hash VARCHAR(64) NOT NULL UNIQUE,
    phone_hash VARCHAR(64) NOT NULL,
    purpose VARCHAR(32) NOT NULL,
    code_hash VARCHAR(64) NOT NULL,
    proof_hash VARCHAR(64),
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    proof_expires_at TIMESTAMP WITH TIME ZONE,
    attempts INTEGER NOT NULL DEFAULT 0,
    last_sent_at TIMESTAMP WITH TIME ZONE NOT NULL,
    resend_available_at TIMESTAMP WITH TIME ZONE NOT NULL,
    verified_at TIMESTAMP WITH TIME ZONE,
    consumed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT auth_challenges_purpose_check
        CHECK (purpose IN ('SIGNUP', 'PASSWORD_RESET')),
    CONSTRAINT auth_challenges_attempts_check CHECK (attempts >= 0)
);

CREATE INDEX idx_auth_challenges_phone_purpose_created
    ON auth_challenges (phone_hash, purpose, created_at DESC);
CREATE UNIQUE INDEX idx_auth_challenges_proof_hash
    ON auth_challenges (proof_hash) WHERE proof_hash IS NOT NULL;
CREATE INDEX idx_auth_challenges_expiry ON auth_challenges (expires_at);
