CREATE TABLE media_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id BIGINT NOT NULL REFERENCES salons(id) ON DELETE CASCADE,
    upload_id UUID NOT NULL,
    media_type VARCHAR(16) NOT NULL,
    object_key TEXT NOT NULL,
    public_url TEXT NOT NULL,
    content_type VARCHAR(64) NOT NULL,
    size_bytes BIGINT NOT NULL,
    etag VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT media_assets_upload_unique UNIQUE (salon_id, upload_id),
    CONSTRAINT media_assets_object_key_unique UNIQUE (object_key),
    CONSTRAINT media_assets_type_check CHECK (media_type IN ('LOGO', 'GALLERY', 'STAFF')),
    CONSTRAINT media_assets_size_check CHECK (size_bytes > 0)
);

CREATE INDEX idx_media_assets_salon_type_created
    ON media_assets(salon_id, media_type, created_at DESC);