package com.hairsaloon.platform;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.hairsaloon.auth.TestUserFactory;
import com.hairsaloon.auth.UserRole;
import jakarta.servlet.http.Cookie;
import java.time.LocalDateTime;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.web.servlet.MockMvc;

@SpringBootTest(properties = {
    "spring.datasource.url=jdbc:h2:mem:customer-features;MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
    "spring.datasource.username=sa", "spring.datasource.password=",
    "spring.datasource.driver-class-name=org.h2.Driver", "spring.flyway.enabled=false",
    "spring.jpa.hibernate.ddl-auto=create-drop", "spring.data.redis.repositories.enabled=false",
    "app.base-domain=localhost", "app.platform-hosts=localhost",
    "app.auth.jwt.secret=raw:0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-extra-secret",
    "app.auth.jwt.issuer=customer-features-test", "app.auth.jwt.ttl=2h",
    "app.auth.cookie.domain=", "app.auth.cookie.secure=false",
    "app.auth.bootstrap-platform-admin.enabled=false"
})
@AutoConfigureMockMvc
class CustomerFeaturesIntegrationTest {
    private static final String HOST = "localhost";

    @Autowired MockMvc mockMvc;
    @Autowired JdbcTemplate jdbc;
    @Autowired TestUserFactory testUsers;

    @BeforeEach
    void clean() {
        jdbc.execute("""
            CREATE TABLE IF NOT EXISTS user_favorites (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              user_id BIGINT NOT NULL, salon_id BIGINT NOT NULL,
              created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
              CONSTRAINT test_user_favorites_unique UNIQUE (user_id, salon_id))
            """);
        jdbc.update("DELETE FROM user_favorites");
        jdbc.update("DELETE FROM notification_outbox");
        jdbc.update("DELETE FROM bookings");
        jdbc.update("DELETE FROM salon_staff");
        jdbc.update("DELETE FROM services");
        jdbc.update("DELETE FROM salons");
        jdbc.update("DELETE FROM users");
    }

    @Test
    void favoritesAreCustomerOnlyIdempotentAndRequireAnActiveSalon() throws Exception {
        TestUserFactory.Identity customer = testUsers.create(
            "favorite-customer@example.com", UserRole.CUSTOMER);
        TestUserFactory.Identity owner = testUsers.create(
            "favorite-owner@example.com", UserRole.SALON_OWNER);
        long salonId = salon(owner.id(), "favorite-salon", "ACTIVE");
        long pendingId = salon(testUsers.create(
            "pending-owner@example.com", UserRole.SALON_OWNER).id(), "pending-salon", "PENDING");

        mockMvc.perform(post("/api/platform/favorites/{salonId}", salonId).header("Host", HOST))
            .andExpect(status().isUnauthorized());
        mockMvc.perform(post("/api/platform/favorites/{salonId}", salonId).header("Host", HOST)
                .cookie(cookie(owner.token())))
            .andExpect(status().isForbidden());
        mockMvc.perform(post("/api/platform/favorites/{salonId}", pendingId).header("Host", HOST)
                .cookie(cookie(customer.token())))
            .andExpect(status().isNotFound())
            .andExpect(jsonPath("$.error").value("SALON_NOT_FOUND"));

        for (int attempt = 0; attempt < 2; attempt++) {
            mockMvc.perform(post("/api/platform/favorites/{salonId}", salonId).header("Host", HOST)
                    .cookie(cookie(customer.token())))
                .andExpect(status().isCreated());
        }
        mockMvc.perform(get("/api/platform/favorites").header("Host", HOST)
                .cookie(cookie(customer.token())))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.length()").value(1))
            .andExpect(jsonPath("$[0].salonId").value(salonId))
            .andExpect(jsonPath("$[0].name").value("Favorite Salon"));

        mockMvc.perform(delete("/api/platform/favorites/{salonId}", salonId).header("Host", HOST)
                .cookie(cookie(customer.token())))
            .andExpect(status().isNoContent());
        mockMvc.perform(get("/api/platform/favorites").header("Host", HOST)
                .cookie(cookie(customer.token())))
            .andExpect(status().isOk()).andExpect(jsonPath("$.length()").value(0));
    }
    @Test
    void bookingHistoryIsScopedAndPasswordChangeInvalidatesTheOldPassword() throws Exception {
        TestUserFactory.Identity customer = testUsers.create(
            "history-customer@example.com", UserRole.CUSTOMER);
        TestUserFactory.Identity otherCustomer = testUsers.create(
            "other-customer@example.com", UserRole.CUSTOMER);
        TestUserFactory.Identity owner = testUsers.create(
            "history-owner@example.com", UserRole.SALON_OWNER);
        long salonId = salon(owner.id(), "history-salon", "ACTIVE");
        long serviceId = service(salonId);
        long staffId = staff(salonId);
        booking(salonId, customer.id(), serviceId, staffId, "Customer Cut");
        booking(salonId, otherCustomer.id(), serviceId, staffId, "Other Cut");

        mockMvc.perform(get("/api/platform/my-bookings").header("Host", HOST)
                .cookie(cookie(customer.token())))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.length()").value(1))
            .andExpect(jsonPath("$[0].salonName").value("Favorite Salon"))
            .andExpect(jsonPath("$[0].serviceName").value("Customer Cut"));

        mockMvc.perform(put("/api/platform/profile/password").header("Host", HOST)
                .cookie(cookie(customer.token())).contentType(MediaType.APPLICATION_JSON)
                .content("{\"currentPassword\":\"WrongPassword!\","
                    + "\"newPassword\":\"ChangedPassword123!\"}"))
            .andExpect(status().isBadRequest())
            .andExpect(jsonPath("$.error").value("INVALID_PASSWORD"));
        mockMvc.perform(put("/api/platform/profile/password").header("Host", HOST)
                .cookie(cookie(customer.token())).contentType(MediaType.APPLICATION_JSON)
                .content("{\"currentPassword\":\"Password123!\","
                    + "\"newPassword\":\"ChangedPassword123!\"}"))
            .andExpect(status().isNoContent());

        mockMvc.perform(post("/api/platform/auth/login").header("Host", HOST)
                .contentType(MediaType.APPLICATION_JSON)
                .content(login(customer.phone(), "Password123!")))
            .andExpect(status().isUnauthorized());
        mockMvc.perform(post("/api/platform/auth/login").header("Host", HOST)
                .contentType(MediaType.APPLICATION_JSON)
                .content(login(customer.phone(), "ChangedPassword123!")))
            .andExpect(status().isOk());
    }

    private long salon(long ownerId, String subdomain, String status) {
        jdbc.update("INSERT INTO salons (owner_id,subdomain,name,address,city,timezone,status,"
                + "cancellation_window_minutes,created_at) "
                + "VALUES (?,?,?,'1 Main','City','UTC',?,120,CURRENT_TIMESTAMP)",
            ownerId, subdomain, "Favorite Salon", status);
        return jdbc.queryForObject("SELECT id FROM salons WHERE owner_id=?", Long.class, ownerId);
    }
    private long service(long salonId) {
        jdbc.update("INSERT INTO services (salon_id,name,duration_minutes,price,is_active,created_at) "
            + "VALUES (?,'Cut',30,35,TRUE,CURRENT_TIMESTAMP)", salonId);
        return jdbc.queryForObject("SELECT id FROM services WHERE salon_id=?", Long.class, salonId);
    }

    private long staff(long salonId) {
        jdbc.update("INSERT INTO salon_staff (salon_id,name,is_active,created_at) "
            + "VALUES (?,'Taylor',TRUE,CURRENT_TIMESTAMP)", salonId);
        return jdbc.queryForObject("SELECT id FROM salon_staff WHERE salon_id=?", Long.class, salonId);
    }

    private void booking(long salonId, long customerId, long serviceId, long staffId,
                         String serviceName) {
        LocalDateTime start = LocalDateTime.now().plusDays(customerId).withNano(0);
        jdbc.update("INSERT INTO bookings (salon_id,customer_id,staff_id,service_id,"
                + "start_datetime,end_datetime,status,price_snapshot,service_name_snapshot,created_at) "
                + "VALUES (?,?,?,?,?,?,'CONFIRMED',35,?,CURRENT_TIMESTAMP)",
            salonId, customerId, staffId, serviceId, start, start.plusMinutes(30), serviceName);
    }

    private static String login(String phone, String password) {
        return "{\"phone\":\"" + phone + "\",\"password\":\"" + password + "\"}";
    }

    private static Cookie cookie(String token) {
        return new Cookie("auth_token", token);
    }
}
