package com.hairsaloon.platform;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import jakarta.servlet.http.Cookie;
import java.math.BigDecimal;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;

@SpringBootTest(properties = {
    "spring.datasource.url=jdbc:h2:mem:platform;MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
    "spring.datasource.username=sa",
    "spring.datasource.password=",
    "spring.datasource.driver-class-name=org.h2.Driver",
    "spring.flyway.enabled=false",
    "spring.jpa.hibernate.ddl-auto=create-drop",
    "spring.data.redis.repositories.enabled=false",
    "app.base-domain=localhost",
    "app.platform-hosts=localhost",
    "app.auth.jwt.secret=raw:0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-extra-secret",
    "app.auth.jwt.issuer=platform-integration-test",
    "app.auth.jwt.ttl=2h",
    "app.auth.cookie.domain=.localhost",
    "app.auth.cookie.secure=false",
    "app.auth.bootstrap-platform-admin.enabled=false"
})
@AutoConfigureMockMvc
class PlatformSalonIntegrationTest {

    private static final String HOST = "localhost";

    @Autowired MockMvc mockMvc;
    @Autowired JdbcTemplate jdbc;
    @Autowired com.hairsaloon.auth.TestUserFactory testUsers;

    @BeforeEach
    void prepareDatabase() {
        jdbc.execute("""
            CREATE TABLE IF NOT EXISTS services (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              salon_id BIGINT NOT NULL, name VARCHAR(160) NOT NULL,
              is_active BOOLEAN NOT NULL)
            """);
        jdbc.execute("DROP TABLE IF EXISTS reviews");
        jdbc.execute("""
            CREATE TABLE reviews (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              salon_id BIGINT NOT NULL, rating SMALLINT NOT NULL)
            """);
        jdbc.update("DELETE FROM reviews");
        jdbc.update("DELETE FROM services");
        jdbc.update("DELETE FROM salon_photos");
        jdbc.update("DELETE FROM salons");
        jdbc.update("DELETE FROM users");
    }
    @Test
    void publicDirectoryExcludesPendingAndSupportsEveryFilterAndStablePagination()
            throws Exception {
        long alpha = salon("alpha-owner@example.com", "alpha", "Alpha Salon",
            "Central", "ACTIVE");
        long beta = salon("beta-owner@example.com", "beta", "Beta Beauty",
            "West", "ACTIVE");
        salon("pending-owner@example.com", "pending", "Pending Salon", "Central", "PENDING");
        service(alpha, "Hair Cut", true);
        service(alpha, "Hidden Facial", false);
        service(beta, "Nail Art", true);
        review(alpha, 5);
        review(alpha, 4);
        review(beta, 3);

        mockMvc.perform(get("/api/platform/salons").header("Host", HOST))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.content.length()").value(2))
            .andExpect(jsonPath("$.content[0].subdomain").value("alpha"))
            .andExpect(jsonPath("$.content[0].rating").value(4.5))
            .andExpect(jsonPath("$.content[0].reviewCount").value(2))
            .andExpect(jsonPath("$.content[0].ownerId").doesNotExist())
            .andExpect(jsonPath("$.totalElements").value(2))
            .andExpect(jsonPath("$.page").value(0))
            .andExpect(jsonPath("$.size").value(20));

        mockMvc.perform(get("/api/platform/salons").header("Host", HOST)
                .param("city", " central "))
            .andExpect(status().isOk()).andExpect(jsonPath("$.totalElements").value(1));
        mockMvc.perform(get("/api/platform/salons").header("Host", HOST)
                .param("service", "hair"))
            .andExpect(status().isOk()).andExpect(jsonPath("$.totalElements").value(1));
        mockMvc.perform(get("/api/platform/salons").header("Host", HOST)
                .param("rating", "4.25"))
            .andExpect(status().isOk()).andExpect(jsonPath("$.totalElements").value(1));
        mockMvc.perform(get("/api/platform/salons").header("Host", HOST)
                .param("search", "alpha"))
            .andExpect(status().isOk()).andExpect(jsonPath("$.totalElements").value(1));

        mockMvc.perform(get("/api/platform/salons").header("Host", HOST)
                .param("city", " central ").param("service", "hair")
                .param("rating", "4.25").param("search", "alpha"))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.content.length()").value(1))
            .andExpect(jsonPath("$.content[0].subdomain").value("alpha"));

        mockMvc.perform(get("/api/platform/salons").header("Host", HOST)
                .param("service", "Hidden"))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.totalElements").value(0));

        mockMvc.perform(get("/api/platform/salons").header("Host", HOST)
                .param("page", "1").param("size", "1"))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.content[0].subdomain").value("beta"))
            .andExpect(jsonPath("$.totalElements").value(2))
            .andExpect(jsonPath("$.totalPages").value(2))
            .andExpect(jsonPath("$.first").value(false))
            .andExpect(jsonPath("$.last").value(true));

        mockMvc.perform(get("/api/platform/salons").header("Host", HOST)
                .param("page", "99").param("size", "1"))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.content.length()").value(0))
            .andExpect(jsonPath("$.totalElements").value(2))
            .andExpect(jsonPath("$.totalPages").value(2));

        mockMvc.perform(get("/api/platform/salons").header("Host", HOST)
                .param("size", "101"))
            .andExpect(status().isBadRequest())
            .andExpect(jsonPath("$.error").value("VALIDATION_ERROR"))
            .andExpect(jsonPath("$.fieldErrors.size").exists());
    }
    @Test
    void subdomainCheckNormalizesAndReportsAvailableReservedTakenAndInvalid() throws Exception {
        String owner = signup("checker@example.com", "SALON_OWNER");
        String customer = signup("customer@example.com", "CUSTOMER");
        salon("existing@example.com", "taken-name", "Taken", "Central", "PENDING");

        mockMvc.perform(get("/api/platform/salons/check-subdomain").header("Host", HOST)
                .cookie(cookie(owner)).param("name", "  Glamour-Studio  "))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.normalized").value("glamour-studio"))
            .andExpect(jsonPath("$.valid").value(true))
            .andExpect(jsonPath("$.available").value(true))
            .andExpect(jsonPath("$.reason").value("AVAILABLE"));

        mockMvc.perform(get("/api/platform/salons/check-subdomain").header("Host", HOST)
                .cookie(cookie(owner)).param("name", " API "))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.normalized").value("api"))
            .andExpect(jsonPath("$.valid").value(false))
            .andExpect(jsonPath("$.available").value(false))
            .andExpect(jsonPath("$.reason").value("RESERVED"));

        mockMvc.perform(get("/api/platform/salons/check-subdomain").header("Host", HOST)
                .cookie(cookie(owner)).param("name", "TAKEN-NAME"))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.normalized").value("taken-name"))
            .andExpect(jsonPath("$.available").value(false))
            .andExpect(jsonPath("$.reason").value("TAKEN"));

        mockMvc.perform(get("/api/platform/salons/check-subdomain").header("Host", HOST)
                .cookie(cookie(owner)).param("name", "-bad"))
            .andExpect(status().isBadRequest())
            .andExpect(jsonPath("$.error").value("VALIDATION_ERROR"))
            .andExpect(jsonPath("$.fieldErrors.name").exists());

        mockMvc.perform(get("/api/platform/salons/check-subdomain").header("Host", HOST))
            .andExpect(status().isUnauthorized());
        mockMvc.perform(get("/api/platform/salons/check-subdomain").header("Host", HOST)
                .cookie(cookie(customer)).param("name", "customer-name"))
            .andExpect(status().isForbidden());
    }

    @Test
    void ownerCreationDerivesOwnershipSanitizesResponseAndAllowsOnlyOneSalon()
            throws Exception {
        String owner = signup("real-owner@example.com", "SALON_OWNER");
        long ownerId = jdbc.queryForObject(
            "SELECT id FROM users WHERE email = 'real-owner@example.com'", Long.class);

        String injectedOwner = createJson("injected-studio", "Injected")
            .replaceFirst("\\{", "{\"ownerId\":999,");
        mockMvc.perform(post("/api/platform/salons").header("Host", HOST)
                .cookie(cookie(owner)).contentType(MediaType.APPLICATION_JSON)
                .content(injectedOwner))
            .andExpect(status().isBadRequest())
            .andExpect(jsonPath("$.error").value("BAD_REQUEST"));

        mockMvc.perform(post("/api/platform/salons").header("Host", HOST)
                .cookie(cookie(owner)).contentType(MediaType.APPLICATION_JSON)
                .content(createJson("  My-Studio  ", "  <b>My Salon</b>  ")))
            .andExpect(status().isCreated())
            .andExpect(jsonPath("$.subdomain").value("my-studio"))
            .andExpect(jsonPath("$.name").value("My Salon"))
            .andExpect(jsonPath("$.description").value("Friendly place"))
            .andExpect(jsonPath("$.email").value("salon@example.com"))
            .andExpect(jsonPath("$.status").value("PENDING"))
            .andExpect(jsonPath("$.ownerId").doesNotExist());

        assertThat(jdbc.queryForObject(
            "SELECT owner_id FROM salons WHERE subdomain = 'my-studio'", Long.class))
            .isEqualTo(ownerId);

        mockMvc.perform(post("/api/platform/salons").header("Host", HOST)
                .cookie(cookie(owner)).contentType(MediaType.APPLICATION_JSON)
                .content(createJson("second-studio", "Second")))
            .andExpect(status().isConflict())
            .andExpect(jsonPath("$.error").value("OWNER_SALON_EXISTS"));
    }
    @Test
    @WithMockUser(roles = "PLATFORM_ADMIN")
    void adminListsPendingApprovesItAndMakesItPublicAndTenantResolvable() throws Exception {
        long pendingId = salon("approval-owner@example.com", "approval", "Approval Salon",
            "Central", "PENDING");
        salon("active-owner@example.com", "other-active", "Other Active", "West", "ACTIVE");

        mockMvc.perform(get("/api/platform/admin/salons/pending").header("Host", HOST))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$[0].id").value(pendingId))
            .andExpect(jsonPath("$[0].description").value("Fixture"))
            .andExpect(jsonPath("$[0].address").value("1 Main Street"))
            .andExpect(jsonPath("$[0].timezone").value("UTC"))
            .andExpect(jsonPath("$[0].ownerEmail").value("approval-owner@example.com"))
            .andExpect(jsonPath("$[0].status").value("PENDING"))
            .andExpect(jsonPath("$[1]").doesNotExist());

        mockMvc.perform(get("/api/platform/salons").header("Host", "approval.localhost"))
            .andExpect(status().isNotFound());

        mockMvc.perform(post("/api/platform/admin/salons/{id}/approve", pendingId)
                .header("Host", HOST))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.status").value("ACTIVE"));

        mockMvc.perform(get("/api/platform/salons").header("Host", HOST)
                .param("search", "Approval"))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.content[0].subdomain").value("approval"));
        mockMvc.perform(get("/api/platform/salons").header("Host", "approval.localhost"))
            .andExpect(status().isOk());

        mockMvc.perform(post("/api/platform/admin/salons/{id}/approve", pendingId)
                .header("Host", HOST))
            .andExpect(status().isConflict())
            .andExpect(jsonPath("$.error").value("INVALID_SALON_STATUS"));
        mockMvc.perform(post("/api/platform/admin/salons/{id}/approve", 999999)
                .header("Host", HOST))
            .andExpect(status().isNotFound())
            .andExpect(jsonPath("$.error").value("SALON_NOT_FOUND"));
    }

    @Test
    void customerOwnerAndAdminRolesAreEnforcedAcrossMutationAndAdminEndpoints()
            throws Exception {
        String customer = signup("roles-customer@example.com", "CUSTOMER");
        String owner = signup("roles-owner@example.com", "SALON_OWNER");

        mockMvc.perform(post("/api/platform/salons").header("Host", HOST)
                .cookie(cookie(customer)).contentType(MediaType.APPLICATION_JSON)
                .content(createJson("customer-salon", "Customer")))
            .andExpect(status().isForbidden());
        mockMvc.perform(get("/api/platform/admin/salons/pending").header("Host", HOST)
                .cookie(cookie(owner)))
            .andExpect(status().isForbidden());
        mockMvc.perform(post("/api/platform/salons").header("Host", HOST)
                .contentType(MediaType.APPLICATION_JSON)
                .content(createJson("anonymous-salon", "Anonymous")))
            .andExpect(status().isUnauthorized());
    }
    @Test
    @WithMockUser(roles = "PLATFORM_ADMIN")
    void platformAdminCannotUseOwnerOnlySalonSignupEndpoints() throws Exception {
        mockMvc.perform(get("/api/platform/salons/check-subdomain").header("Host", HOST)
                .param("name", "admin-studio"))
            .andExpect(status().isForbidden());
        mockMvc.perform(post("/api/platform/salons").header("Host", HOST)
                .contentType(MediaType.APPLICATION_JSON)
                .content(createJson("admin-studio", "Admin")))
            .andExpect(status().isForbidden());
    }

    @Test
    void creationRejectsReservedSubdomainInvalidLogoAndNonIanaTimezone() throws Exception {
        String owner = signup("validation-owner@example.com", "SALON_OWNER");
        mockMvc.perform(post("/api/platform/salons").header("Host", HOST)
                .cookie(cookie(owner)).contentType(MediaType.APPLICATION_JSON)
                .content(createJson("www", "Reserved")))
            .andExpect(status().isBadRequest())
            .andExpect(jsonPath("$.fieldErrors.subdomain").exists());

        mockMvc.perform(post("/api/platform/salons").header("Host", HOST)
                .cookie(cookie(owner)).contentType(MediaType.APPLICATION_JSON)
                .content(createJson("bad-logo", "Logo")
                    .replace("https://cdn.example.com/logo.png", "javascript:alert(1)")))
            .andExpect(status().isBadRequest())
            .andExpect(jsonPath("$.fieldErrors.logoUrl").exists());

        mockMvc.perform(post("/api/platform/salons").header("Host", HOST)
                .cookie(cookie(owner)).contentType(MediaType.APPLICATION_JSON)
                .content(createJson("bad-zone", "Zone")
                    .replace("America/New_York", "Mars/Olympus")))
            .andExpect(status().isBadRequest())
            .andExpect(jsonPath("$.fieldErrors.timezone").exists());
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM salons", Integer.class)).isZero();
    }

    private String signup(String email, String role) {
        return testUsers.create(email,
            com.hairsaloon.auth.UserRole.valueOf(role)).token();
    }

    private long salon(String ownerEmail, String subdomain, String name, String city,
                       String status) {
        testUsers.create(ownerEmail, com.hairsaloon.auth.UserRole.SALON_OWNER);
        long ownerId = jdbc.queryForObject("SELECT id FROM users WHERE email = ?",
            Long.class, ownerEmail);
        jdbc.update("""
            INSERT INTO salons
              (owner_id, subdomain, name, description, address, city, phone, email,
               logo_url, timezone, status, cancellation_window_minutes, created_at)
            VALUES (?, ?, ?, 'Fixture', '1 Main Street', ?, '+1 555 0100', ?,
                    'https://cdn.example.com/logo.png', 'UTC', ?, 120, CURRENT_TIMESTAMP)
            """, ownerId, subdomain, name, city, ownerEmail, status);
        return jdbc.queryForObject("SELECT id FROM salons WHERE subdomain = ?",
            Long.class, subdomain);
    }

    private void service(long salonId, String name, boolean active) {
        jdbc.update("INSERT INTO services (salon_id, name, duration_minutes, price, is_active, created_at) "
                + "VALUES (?, ?, 30, 25.00, ?, CURRENT_TIMESTAMP)",
            salonId, name, active);
    }

    private void review(long salonId, int rating) {
        jdbc.update("INSERT INTO reviews (salon_id, rating) VALUES (?, ?)", salonId, rating);
    }

    private static Cookie cookie(String token) {
        return new Cookie("auth_token", token);
    }

    private static String createJson(String subdomain, String name) {
        return """
            {
              "subdomain":"%s",
              "name":"%s",
              "description":"  <i>Friendly</i> place  ",
              "address":"  10 Main Street  ",
              "city":"  New York  ",
              "phone":" +1 (555) 010-2000 ",
              "email":" Salon@Example.COM ",
              "logoUrl":" https://cdn.example.com/logo.png ",
              "timezone":"America/New_York"
            }
            """.formatted(subdomain, name);
    }
}
